language: python
python:
- pypy
- 2.6
- 2.7
- 3.2
- 3.3
install:
- pip install pytest;
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then
    pip install pytest pytest-cov pep8 coveralls;
  fi
script:
- python -mlibearth.version
- if [ `python -c 'from platform import *; print(python_implementation())'` == 'PyPy' ]; then
    py.test libearth --durations=20 || exit $?;
  else
    py.test --cov libearth --durations=20 || exit $?;
    pep8 || exit $?;
    python docs/coverage.py || exit $?;
  fi
after_success:
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then coveralls; fi
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
