language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
install:
- pip install pytest pytest-cov pep8 coveralls
script:
- python -mlibearth.version
- py.test --cov libearth --durations=20
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then pep8; fi
- python docs/coverage.py
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
