language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
script:
- python -mlibearth.version
- py.test --durations=20
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
